### ISSUE TITLE
You are in the right direction. llama.cpp is really working very fast.

### ISSUE THREAD

**Issue by hiqsociety** [gotzmann/llamazoo#19]
@gotzmann pls help get windows compatibility / macos compilation working too

i'm not very well versed in this but do mention how you think ordinary golang dev can help you speed up your work.

pls help make it zero dependencies as possible so it can be installed on all devices easily.

Thanks!

**Comment by gotzmann** [comment]
At this point we had successfully compiled LLaMAZoo for:

- Mac with Apple Silicon (CPU and GPU are supported)
- Linux on AMD and ARM chips (both CPU and GPU are supported as well)

We are going to check out Windows compatibility soon.
